import type { Metadata } from "next";
import { Press_Start_2P, Space_Grotesk } from "next/font/google";
import "./globals.css";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ['latin'],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap"
})

const pressStart = Press_Start_2P({
  variable: "--font-press-start",
  subsets: ['latin'],
  display: 'swap',
  weight: ['400']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${pressStart.variable} ${spaceGrotesk.variable} font-headline h-full antialiased`}
    >
      <body className="min-h-full w-full flex flex-col bg-black">
        {children}
      </body>
    </html>
  );
}
